### your site title here
# git push origin gh-pages

title: Улучшение взаимопонимания и эмпатия
description:

baseurl: "" #name of GitHub repository
url: "https://ivanbek.ru" #custom url to be used instead of GitHub repository
email: #
repository: ivanbeknno/ivanbeknno.github.io

locale: "ru_RU"
timezone: Europe/Moscow

highlighter: rouge
markdown: kramdown

# Pagination
paginate: 20
permalink: /blog/:year/:month/:title/
paginate_path: /blog/:num/

# Social media links in footer
facebook: #
twitter: #
linkedin: #
researchgate: #
orcid: #

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!--", "-->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /cases/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

feed:
  path: /feed.atom

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
  - jekyll-feed
