name: Scheduled Site Build

on:
  schedule:
    # Запускать в 16:32 UTC (19:32 MSK)
    - cron: '32 16 * * *'
    # Запускать в 13:32 UTC (16:32 MSK)
    - cron: '32 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонировать репозиторий
      - uses: actions/checkout@v4

      # Шаг 2: Триггер пересборки через API
      - name: Trigger GitHub Pages rebuild
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds
